Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 07/08/2020
Var
// Seção de Declarações das variáveis 
N1, N2, media: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval ("N1: ")
 leia (N1)
 escreval ("N2: ")
 leia (N2)
 media <- (N1+N2)/2
 se media >= 6 entao
 escreval ("Voce foi aprovado")
 senao
 escreval ("Voce foi reprovado")
 fimse

Fimalgoritmo